### ISSUE TITLE
getcwd() crashes or shows garbage result

### ISSUE THREAD

**Issue by cdbennett** [sectordistrict/intentrace#7]
It appears that `intentrace` isn't handling the output of the `getcwd()` function properly. Depending on the program being traced, it can print random non-printable characters as the result, or even cause `intentrace` to panic.

UPDATE: After further research, it appears that we need to teach intentrace which pointers passed to system calls are input vs. output buffers. A relevant comment is in [syscalls_map.rs](https://github.com/sectordistrict/intentrace/blob/main/src/syscalls_map.rs#L10C3-L10C125):
`clarify whether a buffer is provided by the user or to be filled by the kernel in the name of the argument (GIVE vs FILL)`

Tested with intentrace 0.2.4 and Git main branch (at 11da6ad)

## Example: Python - prints garbage

```text
intentrace$ RUST_BACKTRACE=1 target/debug/intentrace python -c 'import os; print("Hello", os.getcwd())'
[...]
750898 stat - get the stats of the file: /home/cdb/miniforge3/lib/python3.10/site-packages |=> stats retrieved successfully
750898 getcwd - get the current working directory |=> cwd: �C�
                                                              �U
750898 write - write 32 Bytes into the file: 1 -> StdOut |=> wrote all 32 Bytes
Hello /home/cdb/Code/intentrace
```

Example: cargo - prints garbage and crashes
(crash might be due to cargo using a GNU extension that allows the caller to pass NULL as the buffer and then `getcwd()` is expected to allocate the buffer itself)

```text
intentrace$ RUST_BACKTRACE=1 target/debug/intentrace cargo version

749927 brk - get the current program break |=> current program break: 0x55d1a58f9000
[...]
749927 ioctl - perform operation #21505 on the device: 2 -> StdErr |=> operation successful
749927 ioctl - perform operation #21505 on the device: 1 -> StdOut |=> operation successful
749927 getcwd - get the current working directory |=> cwd: �����U
749927 readlink - get the target path of the symbolic link: /proc/self/exe |=> target retrieved: /home/cdb/.cargo/bin/cargo
749927 getcwd - get the current working directory |=> cwd: �X]
thread 'main' panicked at src/syscall_object.rs:1330:82:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:148:5
   3: core::option::unwrap_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:2015:5
   4: core::option::Option<T>::unwrap
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:965:21
   5: intentrace::syscall_object::SyscallObject::string_from_pointer
             at ./src/syscall_object.rs:1330:20
   6: intentrace::syscall_object::SyscallObject::get_precall_data
             at ./src/syscall_object.rs:957:33
   7: intentrace::syscall_will_run
             at ./src/main.rs:303:5
   8: intentrace::parent
             at ./src/main.rs:172:33
   9: intentrace::runner
             at ./src/main.rs:93:21
  10: intentrace::main
             at ./src/main.rs:77:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
749927 statx - get the stats of the file: /home/cdb/.cargo/bin/rustup-init |=> No such file or directory
cargo 1.82.0 (8f40fc59f 2024-08-21)
```

## Example: /usr/bin/pwd - prints nothing

```text
intentrace$ RUST_BACKTRACE=1 target/debug/intentrace /usr/bin/pwd
[...]
750359 getcwd - get the current working directory |=> cwd:
/home/cdb/Code/intentrace
```

Environment: Debian Linux 12, x86_64
Rust 1.82.0

**Comment by cdbennett** [comment]
I also tried a minimal C program that calls `getcwd()`. Seems now that `intentrace` is printing whatever the buffer passed in to `getcwd()` had when it is called. This isn't valid since an uninitialized buffer can (and usually is) passed to `getcwd()`.

test program:

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
    char buf[300] = "<<UNINITIALIZED>>";

    fprintf(stderr, "# testing getcwd() POSIX mode with caller-provided stack buffer:\n");
    if (getcwd(buf, sizeof buf) == NULL) {
        fprintf(stderr, "ERROR: getcwd failed\n");
        return 1;
    }
    fprintf(stderr, "my working directory is '%s'\n", buf);

    return 0;
}
```

Running it prints "<<UNINITIALIZED>>":

```text
$ intentrace ./getcwd
...
758044 getcwd - get the current working directory |=> cwd: <<UNINITIALIZED>>
758044 write - write 64 Bytes into the file: 2 -> StdErr |=> wrote all 64 Bytesmy working directory is '/home/cdb/Code/intentrace/test-getcwd'
```

**Comment by sectordistrict** [comment]
It already knows that, infact `getcwd` has its own special return type which the function `get_postcall_data` checks for (of course this is not ideal)

the cause of the current problem with gibberish output is that the `getcwd` logic was looking for the buffer in the first syscall argument instead of the syscall return, I will push the new changes under 0.2.5, 

thank you for the detailed issue report
